---

# Monitor Number  = 28
# Mobile Phone 1 Mac: #M0B1LEMAC1#
# Mobile Phone 2 Mac: #M0B1LEMAC2#

- name: "Session Initiation Protocol"
  hosts: cucm
  gather_facts: no
  become: yes
  tasks:
    - name: "Allow SIP Connections"
      ios_command: 
        commands: 
          - conf t
          - voice service voip
          - allow-connections h323 to sip
          - allow-connections sip to h323
          - allow-connections sip to sip
          - supplementary-service h450.12
          - sip
          - bind control source-interface fa0/0
          - bind media source-interface fa0/0
          - registrar server expires max 600 min 60
          - end
      tags: 
        - allowsip
      

    - name: "Assign SIP Domain"
      ios_command:
        commands:
          - config t
          - voice register global
          - mode cme
          - "source-address 10.28.100.8 port 5060"
          - max-dn 12
          - max-pool 12
          - authenticate register
          - create profile
          - end
      tags:
        - sipdomain
      

    - name: "Create Directory Numbers"
      ios_command:
        commands: 
          - config t
          - voice register dn 1
          - "number 2834"
          - allow watch
          - "name 2834"
          - voice register dn 2
          - "number 2843"
          - allow watch
          - "name 2843"
          - end
      tags:
        - sipdn
    
    - name: "Register Accounts"
      ios_command:
        commands: 
          - config t
          - voice register pool 1
          - "id mac #M0B1LEMAC1#"
          - number 1 dn 1
          - dtmf-relay sip-notify
          - "username 2823 password 2823"
          - codec g711ulaw
          - voice register pool 2
          - "id mac #M0B1LEMAC2#"
          - number 1 dn 2
          - dtmf-relay sip-notify
          - "username 2832 password 2832"
          - codec g711ulaw
          - end
      tags:
        - register
