---
- name: Configure Loop 100
  hosts: Im-A-Node
  gather_facts: no
  become: yes
  
  tasks: 
    - name: Adding Loop 100
      ios_command:
        commands:
          - conf t
          - int loopback 100
          - ip add 100.100.100.100 255.255.255.255
          - end
      tags:
        - addloop